# Generated by Django 2.0.6 on 2018-09-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_object',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived?'),
        ),
    ]
